courier-imap: sanity checking of some config settings at startup.

diff --git a/courier-imap/imapd.rc.in b/courier-imap/imapd.rc.in
--- a/courier-imap/imapd.rc.in
+++ b/courier-imap/imapd.rc.in
@@ -36,12 +36,21 @@ start)
 		chmod 600  "$TLS_CACHEFILE"
 	fi
 
+	umask ${IMAP_UMASK:=022}
 	if test ! -f "${IMAPACCESSFILE}.dat"
 	then
-		@bindir@/makeimapaccess
+		if test -e "${IMAPACCESSFILE}"
+		then
+			@bindir@/makeimapaccess
+		else
+			echo "IMAPACCESSFILE is missing." >&2
+			exit 1
+		fi
 	fi
-	umask $IMAP_UMASK
-	@ULIMIT@ $IMAP_ULIMITD
+	if test ! -z "$IMAP_ULIMITD"
+	then
+		@ULIMIT@ $IMAP_ULIMITD
+	fi
 	@SETENV@ -i @SHELL@ -c " set -a ;
 			prefix=@prefix@ ;
 			exec_prefix=@exec_prefix@ ;
